spring:
  datasource:
    url: ${PROD_DB_URL:jdbc:postgresql://localhost:5432/app_production}
    username: ${PROD_DB_USERNAME:prod_user}
    password: ${PROD_DB_PASSWORD:prod_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}
  compression:
    enabled: true
    min-response-size: 1024

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.mewebstudio.javaspringbootboilerplate: INFO
  file:
    name: ${LOG_FILE:logs/application-production.log}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
